config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  match "posts/:id" => "posts#show", :via => 'post', :as => :post
  root 'posts#index'
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :post

    validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments

    validates :tittle, presence: true
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :posts
has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /comments
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post_id = @post.id
    @comment.user_id = current_user.id
    @post.comments << @comment

    if @comment.save!
      redirect_to @post
    else
      render 'posts/show'
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to @comment
    else
      render :edit
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to comments_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    @post.user_id = current_user.id
    @post.comments = Array.new

    if @post.save
      redirect_to @post#, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post#, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url#, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:tittle, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |form| %>

  <div class="field">
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_new.html.erb
<h1>New Comment</h1>

<%= render 'comments/form', comment: @comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tittle %>
    <%= form.text_field :tittle, id: :post_tittle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<html>

<head>
    <%= stylesheet_link_tag "agency.css" %>
    <%= stylesheet_link_tag "styles.css" %>
</head>

<body style="margin: 10px">
    <div class="nav-bar">
        <%= image_tag("logos/logo.png", :alt => "Ruby Blog", :class => "logo") %>
        <div class="menu-buttons">
            <a href="/posts#Home">Home</a>
        </div>

        <div class="menu-buttons">
            <a href="/posts#Posts">Posts</a>
        </div>

        <div class="menu-buttons">
            <a href="/posts/new">Create new Post </a>
        </div>

        <div class="menu-buttons">
            <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            <% else %>
            <%= link_to "Log In", new_user_session_path %>
            <% end %>
        </div>

        <div class="user">
            <% if user_signed_in? %>
            <p style="font-size: 16px"><%= current_user.email %>, <%= Post.where(user_id: current_user.id).count %> posts</p>
            <% end %>
        </div>
    </div>
    <h1 class="header">Editing Post</h1>

    <%= render 'form', post: @post %>

    <%= link_to 'Show', @post, :style => 'font-size: 18px;' %> |
    <%= link_to 'Back', posts_path, :style => 'font-size: 18px;' %>
</body>

</html>

app/views/posts/index.html.erb
<html>

<head>
    <%= stylesheet_link_tag "agency.css" %>
    <%= stylesheet_link_tag "styles.css" %>
    <title>Ruby Blog</title>
</head>

<body>
    <div class="nav-bar">
        <%= image_tag("logos/logo.png", :alt => "Ruby Blog", :class => "logo") %>
        <div class="menu-buttons">
            <a href="/posts#Home">Home</a>
        </div>

        <div class="menu-buttons">
            <a href="/posts#Posts">Posts</a>
        </div>

        <div class="menu-buttons">
            <a href="/posts/new">Create new Post </a>
        </div>

        <div class="menu-buttons">
            <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            <% else %>
            <%= link_to "Log In", new_user_session_path %>
            <% end %>
        </div>

        <div class="user">
            <% if user_signed_in? %>
            <p style="font-size: 16px"><%= current_user.email %>, <%= Post.where(user_id: current_user.id).count %> posts</p>
            <% end %>
        </div>
    </div>

    <div>
        <%= image_tag("blog.jpg", :alt => "Blog", :class => "blog-img", :id => "Home") %>
    </div>
    <div id="Posts"></div>
    <div style="margin-left: 10px; margin-right: 10px;">
        <p class="header" >Posts</p>
        <p class="post-body">Read another users' posts or just <a href="/posts/new"> create new post here </a></p>

        <% @posts.each do |post| %>

        <p class="post-title" style="vertical-align: bottom; margin: 0;"><%= post.tittle %></p>
        <p class="post-body"><%= post.body[0..400] %> ... </p>
        <p class="post-author" style="vertical-align: bottom; margin: 0;"> Author: <%= post.user.email %></p>
        <p class="post-time"><%= time_ago_in_words(post.created_at) %> ago</p>

        <%= link_to 'Show', post %>
        <% if post.user == current_user %>
        | <%= link_to 'Edit', edit_post_path(post) %> | 
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        <hr>
        <% end %>

    </div>
</body>

</html>

app/views/posts/new.html.erb
<html>

<head>
    <%= stylesheet_link_tag "agency.css" %>
    <%= stylesheet_link_tag "styles.css" %>

</head>

<body style="margin: 10px">

<div class="nav-bar">
        <%= image_tag("logos/logo.png", :alt => "Ruby Blog", :class => "logo") %>
        <div class="menu-buttons">
            <a href="/posts#Home">Home</a>
        </div>

        <div class="menu-buttons">
            <a href="/posts#Posts">Posts</a>
        </div>

        <div class="menu-buttons">
            <a href="/posts/new">Create new Post </a>
        </div>

        <div class="menu-buttons">
            <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            <% else %>
            <%= link_to "Log In", new_user_session_path %>
            <% end %>
        </div>

        <div class="user">
            <% if user_signed_in? %>
            <p style="font-size: 16px"><%= current_user.email %>, <%= Post.where(user_id: current_user.id).count %> posts</p>
            <% end %>
        </div>
    </div>

    <h1 class="header">New Post</h1>

    <%= render 'form', post: @post %>
    <br>
    <%= link_to 'Back', posts_path, :style => 'font-size: 18px;' %>
    <title>New Post</title>
</body>

</html>

app/views/posts/show.html.erb
<html>

<head>
    <%= stylesheet_link_tag "agency.css" %>
    <%= stylesheet_link_tag "styles.css" %>
</head>

<body style="margin: 10px">
<div class="nav-bar">
        <%= image_tag("logos/logo.png", :alt => "Ruby Blog", :class => "logo") %>
        <div class="menu-buttons">
            <a href="/posts#Home">Home</a>
        </div>

        <div class="menu-buttons">
            <a href="/posts#Posts">Posts</a>
        </div>

        <div class="menu-buttons">
            <a href="/posts/new">Create new Post </a>
        </div>

        <div class="menu-buttons">
            <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            <% else %>
            <%= link_to "Log In", new_user_session_path %>
            <% end %>
        </div>

        <div class="user">
            <% if user_signed_in? %>
            <p style="font-size: 16px"><%= current_user.email %>, <%= Post.where(user_id: current_user.id).count %> posts</p>
            <% end %>
        </div>
    </div>
    <p id="notice"><%= notice %></p>

    <h1 class="header"><%= @post.tittle %></h1>

    <p class="post-body"><%= @post.body %></p>
    <p class="post-author" style="vertical-align: bottom; margin: 0;"> Author: <%= @post.user.email %> </p>
    <p class="post-time"><%= time_ago_in_words(@post.created_at) %> ago</p>

    <% if @post.user == current_user %>
        | <%= link_to 'Edit', edit_post_path(@post), :style => 'font-size: 18px;' %> | 
        <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, :style => 'font-size: 18px;' %> |
    <% end %>

    <%= link_to 'Back', posts_path, :style => 'font-size: 18px;' %>

    <p><%= @post.comments.length %> Comment(s)</p>

    <%= render 'comments/new' %>
    <hr>
    <% @post.comments.all.each do |c|%>
    <p class="comm-body"> <%= c.body %> </p>
    <p class="comm-author"> <%= User.find(c.user_id).email%>,
    <%= time_ago_in_words(c.created_at) %> ago</p>
    <hr>
    <% end %>
</body>

</html>